package duit_animations

type Curves = string

const (
	// Standard Flutter Curves
	Linear                  Curves = "linear"
	Decelerate              Curves = "decelerate"
	FastLinearToSlowEaseIn  Curves = "fastLinearToSlowEaseIn"
	Ease                    Curves = "ease"
	EaseIn                  Curves = "easeIn"
	EaseInToLinear          Curves = "easeInToLinear"
	EaseInSine              Curves = "easeInSine"
	EaseInQuad              Curves = "easeInQuad"
	EaseInCubic             Curves = "easeInCubic"
	EaseInQuart             Curves = "easeInQuart"
	EaseInQuint             Curves = "easeInQuint"
	EaseInExpo              Curves = "easeInExpo"
	EaseInCirc              Curves = "easeInCirc"
	EaseInBack              Curves = "easeInBack"
	EaseOut                 Curves = "easeOut"
	LinearToEaseOut         Curves = "linearToEaseOut"
	EaseOutSine             Curves = "easeOutSine"
	EaseOutQuad             Curves = "easeOutQuad"
	EaseOutCubic            Curves = "easeOutCubic"
	EaseOutQuart            Curves = "easeOutQuart"
	EaseOutQuint            Curves = "easeOutQuint"
	EaseOutExpo             Curves = "easeOutExpo"
	EaseOutCirc             Curves = "easeOutCirc"
	EaseOutBack             Curves = "easeOutBack"
	EaseInOut               Curves = "easeInOut"
	EaseInOutSine           Curves = "easeInOutSine"
	EaseInOutQuad           Curves = "easeInOutQuad"
	EaseInOutCubic          Curves = "easeInOutCubic"
	EaseInOutQuart          Curves = "easeInOutQuart"
	EaseInOutQuint          Curves = "easeInOutQuint"
	EaseInOutExpo           Curves = "easeInOutExpo"
	EaseInOutCirc           Curves = "easeInOutCirc"
	EaseInOutBack           Curves = "easeInOutBack"
	FastOutSlowIn           Curves = "fastOutSlowIn"
	SlowMiddle              Curves = "slowMiddle"
	BounceIn                Curves = "bounceIn"
	BounceOut               Curves = "bounceOut"
	BounceInOut             Curves = "bounceInOut"
	ElasticIn               Curves = "elasticIn"
	ElasticOut              Curves = "elasticOut"
	ElasticInOut            Curves = "elasticInOut"
	
	// Material Design 3 curves (additional)
	EaseInOutCubicEmphasized Curves = "easeInOutCubicEmphasized"
)
