package duit_animations

type Curves string

const (
	linear                   Curves = "linear"
	fastEaseInToSlowEaseOut  Curves = "fastEaseInToSlowEaseOut"
	bounceIn                 Curves = "bounceIn"
	bounceInOut              Curves = "bounceInOut"
	bounceOut                Curves = "bounceOut"
	decelerate               Curves = "decelerate"
	ease                     Curves = "ease"
	easeIn                   Curves = "easeIn"
	easeInBack               Curves = "easeInBack"
	easeInCirc               Curves = "easeInCirc"
	easeInSine               Curves = "easeInSine"
	easeInCubic              Curves = "easeInCubic"
	easeInExpo               Curves = "easeInExpo"
	easeInOutCubicEmphasized Curves = "easeInOutCubicEmphasized"
	easeInOutBack            Curves = "easeInOutBack"
	easeInOutCirc            Curves = "easeInOutCirc"
	easeInOutExpo            Curves = "easeInOutExpo"
	easeInOutQuad            Curves = "easeInOutQuad"
	easeInOutQuart           Curves = "easeInOutQuart"
	easeInOutQuint           Curves = "easeInOutQuint"
	easeInOutSine            Curves = "easeInOutSine"
	easeInToLinear           Curves = "easeInToLinear"
	easeOutSine              Curves = "easeOutSine"
	easeOutBack              Curves = "easeOutBack"
	easeOutCirc              Curves = "easeOutCirc"
	easeOutCubic             Curves = "easeOutCubic"
	easeOutExpo              Curves = "easeOutExpo"
	easeOutQuad              Curves = "easeOutQuad"
	easeOutQuart             Curves = "easeOutQuart"
	easeOutQuint             Curves = "easeOutQuint"
	linearToEaseOut          Curves = "linearToEaseOut"
	slowMiddle               Curves = "slowMiddle"
	fastOutSlowIn            Curves = "fastOutSlowIn"
	elasticIn                Curves = "elasticIn"
	elasticInOut             Curves = "elasticInOut"
	elasticOut               Curves = "elasticOut"
)
